let
    SourcePath = MonthlyOutputRoot & "\\kpi_monthly_summary.csv",
    Source = Csv.Document(
        File.Contents(SourcePath),
        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
    ),
    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    TypedColumns = Table.TransformColumnTypes(
        PromotedHeaders,
        {
            {"site_id", type text},
            {"period", type text},
            {"throughput_tonnes_plan", Int64.Type},
            {"head_grade_pct_plan", type number},
            {"recovery_pct_plan", type number},
            {"unit_cost_usd_per_tonne_plan", type number},
            {"copper_price_usd_per_lb_plan", type number},
            {"tc_rc_usd_per_lb_plan", type number},
            {"payable_percent_plan", type number},
            {"sustaining_capex_usd_plan", Int64.Type},
            {"working_capital_change_usd_plan", Int64.Type},
            {"plan_version", type text},
            {"throughput_tonnes_actual", Int64.Type},
            {"copper_production_tonnes_actual", Int64.Type},
            {"head_grade_pct_actual", type number},
            {"recovery_pct_actual", type number},
            {"availability_pct_actual", type number},
            {"utilization_pct_actual", type number},
            {"downtime_hours_actual", Int64.Type},
            {"mining_cost_usd_actual", Int64.Type},
            {"processing_cost_usd_actual", Int64.Type},
            {"ga_cost_usd_actual", Int64.Type},
            {"sustaining_capex_usd_actual", Int64.Type},
            {"working_capital_change_usd_actual", Int64.Type},
            {"copper_price_usd_per_lb_actual", type number},
            {"tc_rc_usd_per_lb_actual", type number},
            {"payable_percent_actual", type number},
            {"benchmark_price_name", type text},
            {"month_start_date", type text},
            {"calendar_year", Int64.Type},
            {"calendar_month", Int64.Type},
            {"calendar_quarter", Int64.Type},
            {"month_label", type text},
            {"operating_cost_usd_plan", type number},
            {"operating_cost_usd_actual", Int64.Type},
            {"unit_cost_usd_per_tonne_actual", type number},
            {"copper_production_tonnes_plan", type number},
            {"net_realized_price_usd_per_lb_plan", type number},
            {"net_realized_price_usd_per_lb_actual", type number},
            {"revenue_proxy_usd_plan", type number},
            {"revenue_proxy_usd_actual", type number},
            {"ebitda_proxy_usd_plan", type number},
            {"ebitda_proxy_usd_actual", type number},
            {"operating_cash_flow_proxy_usd_plan", type number},
            {"operating_cash_flow_proxy_usd_actual", type number},
            {"free_cash_flow_proxy_usd_plan", type number},
            {"free_cash_flow_proxy_usd_actual", type number},
            {"throughput_tonnes_variance", Int64.Type},
            {"throughput_tonnes_variance_pct", type number},
            {"head_grade_pct_variance", type number},
            {"head_grade_pct_variance_pct", type number},
            {"recovery_pct_variance", type number},
            {"recovery_pct_variance_pct", type number},
            {"copper_production_tonnes_variance", type number},
            {"copper_production_tonnes_variance_pct", type number},
            {"copper_price_usd_per_lb_variance", type number},
            {"copper_price_usd_per_lb_variance_pct", type number},
            {"net_realized_price_usd_per_lb_variance", type number},
            {"net_realized_price_usd_per_lb_variance_pct", type number},
            {"unit_cost_usd_per_tonne_variance", type number},
            {"unit_cost_usd_per_tonne_variance_pct", type number},
            {"operating_cost_usd_variance", type number},
            {"operating_cost_usd_variance_pct", type number},
            {"revenue_proxy_usd_variance", type number},
            {"revenue_proxy_usd_variance_pct", type number},
            {"ebitda_proxy_usd_variance", type number},
            {"ebitda_proxy_usd_variance_pct", type number},
            {"operating_cash_flow_proxy_usd_variance", type number},
            {"operating_cash_flow_proxy_usd_variance_pct", type number},
            {"free_cash_flow_proxy_usd_variance", type number},
            {"free_cash_flow_proxy_usd_variance_pct", type number},
            {"sustaining_capex_usd_variance", Int64.Type},
            {"sustaining_capex_usd_variance_pct", type number},
            {"working_capital_change_usd_variance", Int64.Type},
            {"working_capital_change_usd_variance_pct", type number},
            {"site_name", type text},
            {"data_classification", type text},
            {"sample_data_flag", type logical},
            {"critical_alert_count", Int64.Type},
            {"warning_alert_count", Int64.Type},
            {"primary_alert_metric", type text},
            {"primary_alert_message", type text},
            {"overall_alert_level", type text},
            {"stockpile_feed_pct_actual", type number},
            {"primary_process_area", type text},
            {"primary_ore_source", type text},
            {"primary_process_area_downtime_hours", Int64.Type},
            {"top_cost_center", type text},
            {"top_cost_center_variance_usd", Int64.Type},
            {"top_cost_center_margin_pressure_share_pct", type number},
            {"site_positive_cost_variance_usd", Int64.Type},
            {"site_production_gap_tonnes", type number},
            {"site_production_gap_share_pct", type number},
            {"site_cost_pressure_share_pct", type number}
        }
    )
in
    TypedColumns
