"""Semantic layer helpers for BI exports."""

from __future__ import annotations

import pandas as pd


METRIC_CATEGORY_MAP = {
    "base_processed_tonnes": "Operations",
    "expanded_tonnes": "Operations",
    "scenario_price_usd_per_lb": "Market",
    "scenario_grade": "Geology",
    "scenario_recovery": "Metallurgy",
    "scenario_net_price_usd_per_lb": "Commercial",
    "copper_fine_lb": "Production",
    "gross_revenue_usd": "Economics",
    "payable_revenue_usd": "Economics",
    "tcrc_usd": "Commercial",
    "revenue_usd": "Economics",
    "unit_opex_usd_per_tonne": "Economics",
    "opex_usd": "Economics",
    "ebitda_usd": "Economics",
    "cash_tax_proxy_usd": "Economics",
    "operating_cash_flow_usd": "Cash Flow",
    "initial_capex_usd": "Investment",
    "sustaining_capex_usd": "Investment",
    "capex_usd": "Investment",
    "working_capital_investment_usd": "Working Capital",
    "working_capital_release_usd": "Working Capital",
    "working_capital_delta_usd": "Working Capital",
    "free_cash_flow_usd": "Cash Flow",
    "discounted_fcf_usd": "Valuation",
}


def build_metric_catalog() -> pd.DataFrame:
    return pd.DataFrame(
        [
            {"metric": "base_processed_tonnes", "display_name": "Base Processed Tonnes", "unit": "tonnes", "category": "Operations", "dashboard_page": "Throughput and Production"},
            {"metric": "expanded_tonnes", "display_name": "Expanded Processed Tonnes", "unit": "tonnes", "category": "Operations", "dashboard_page": "Throughput and Production"},
            {"metric": "scenario_price_usd_per_lb", "display_name": "Copper Price", "unit": "USD/lb", "category": "Market", "dashboard_page": "Scenario Planning and Price Exposure"},
            {"metric": "scenario_grade", "display_name": "Head Grade", "unit": "decimal", "category": "Geology", "dashboard_page": "Grade and Recovery"},
            {"metric": "scenario_recovery", "display_name": "Recovery", "unit": "decimal", "category": "Metallurgy", "dashboard_page": "Grade and Recovery"},
            {"metric": "scenario_net_price_usd_per_lb", "display_name": "Net Realized Price", "unit": "USD/lb", "category": "Commercial", "dashboard_page": "Scenario Planning and Price Exposure"},
            {"metric": "copper_fine_lb", "display_name": "Copper Fine Production", "unit": "lb", "category": "Production", "dashboard_page": "Throughput and Production"},
            {"metric": "gross_revenue_usd", "display_name": "Gross Revenue", "unit": "USD", "category": "Economics", "dashboard_page": "Cost, Revenue and Cash Generation"},
            {"metric": "payable_revenue_usd", "display_name": "Payable Revenue", "unit": "USD", "category": "Economics", "dashboard_page": "Cost, Revenue and Cash Generation"},
            {"metric": "tcrc_usd", "display_name": "Treatment and Refining Charges", "unit": "USD", "category": "Commercial", "dashboard_page": "Cost, Revenue and Cash Generation"},
            {"metric": "revenue_usd", "display_name": "Revenue", "unit": "USD", "category": "Economics", "dashboard_page": "Cost, Revenue and Cash Generation"},
            {"metric": "unit_opex_usd_per_tonne", "display_name": "Unit Opex", "unit": "USD/t", "category": "Economics", "dashboard_page": "Cost, Revenue and Cash Generation"},
            {"metric": "opex_usd", "display_name": "Operating Cost", "unit": "USD", "category": "Economics", "dashboard_page": "Cost, Revenue and Cash Generation"},
            {"metric": "ebitda_usd", "display_name": "EBITDA", "unit": "USD", "category": "Economics", "dashboard_page": "Cost, Revenue and Cash Generation"},
            {"metric": "cash_tax_proxy_usd", "display_name": "Cash Tax Proxy", "unit": "USD", "category": "Economics", "dashboard_page": "Cost, Revenue and Cash Generation"},
            {"metric": "operating_cash_flow_usd", "display_name": "Operating Cash Flow", "unit": "USD", "category": "Cash Flow", "dashboard_page": "Cost, Revenue and Cash Generation"},
            {"metric": "initial_capex_usd", "display_name": "Initial Capex", "unit": "USD", "category": "Investment", "dashboard_page": "Advanced Valuation and Downside Risk"},
            {"metric": "sustaining_capex_usd", "display_name": "Sustaining Capex", "unit": "USD", "category": "Investment", "dashboard_page": "Cost, Revenue and Cash Generation"},
            {"metric": "capex_usd", "display_name": "Capex", "unit": "USD", "category": "Investment", "dashboard_page": "Cost, Revenue and Cash Generation"},
            {"metric": "working_capital_investment_usd", "display_name": "Working Capital Investment", "unit": "USD", "category": "Working Capital", "dashboard_page": "Cost, Revenue and Cash Generation"},
            {"metric": "working_capital_release_usd", "display_name": "Working Capital Release", "unit": "USD", "category": "Working Capital", "dashboard_page": "Cost, Revenue and Cash Generation"},
            {"metric": "working_capital_delta_usd", "display_name": "Working Capital Delta", "unit": "USD", "category": "Working Capital", "dashboard_page": "Cost, Revenue and Cash Generation"},
            {"metric": "free_cash_flow_usd", "display_name": "Free Cash Flow", "unit": "USD", "category": "Cash Flow", "dashboard_page": "Cost, Revenue and Cash Generation"},
            {"metric": "discounted_fcf_usd", "display_name": "Discounted FCF", "unit": "USD", "category": "Valuation", "dashboard_page": "Advanced Valuation and Downside Risk"},
        ]
    )


def build_kpi_catalog() -> pd.DataFrame:
    return pd.DataFrame(
        [
            {"metric": "total_revenue_usd", "display_name": "Total Revenue", "unit": "USD", "dashboard_page": "Executive Planning Overview"},
            {"metric": "total_ebitda_usd", "display_name": "Total EBITDA", "unit": "USD", "dashboard_page": "Executive Planning Overview"},
            {"metric": "total_opex_usd", "display_name": "Total Opex", "unit": "USD", "dashboard_page": "Executive Planning Overview"},
            {"metric": "total_operating_cash_flow_usd", "display_name": "Total Operating Cash Flow", "unit": "USD", "dashboard_page": "Executive Planning Overview"},
            {"metric": "total_capex_usd", "display_name": "Total Capex", "unit": "USD", "dashboard_page": "Executive Planning Overview"},
            {"metric": "total_free_cash_flow_usd", "display_name": "Total Free Cash Flow", "unit": "USD", "dashboard_page": "Executive Planning Overview"},
            {"metric": "average_processed_tonnes", "display_name": "Average Throughput", "unit": "tonnes", "dashboard_page": "Executive Planning Overview"},
            {"metric": "average_copper_fine_lb", "display_name": "Average Copper Fine Production", "unit": "lb", "dashboard_page": "Executive Planning Overview"},
            {"metric": "average_unit_opex_usd_per_tonne", "display_name": "Average Unit Opex", "unit": "USD/t", "dashboard_page": "Executive Planning Overview"},
            {"metric": "average_net_price_usd_per_lb", "display_name": "Average Net Price", "unit": "USD/lb", "dashboard_page": "Scenario Planning and Price Exposure"},
            {"metric": "average_head_grade", "display_name": "Average Head Grade", "unit": "decimal", "dashboard_page": "Executive Planning Overview"},
            {"metric": "average_recovery", "display_name": "Average Recovery", "unit": "decimal", "dashboard_page": "Executive Planning Overview"},
            {"metric": "ebitda_margin_proxy", "display_name": "EBITDA Margin Proxy", "unit": "decimal", "dashboard_page": "Executive Planning Overview"},
            {"metric": "scenario_npv_usd", "display_name": "Scenario NPV", "unit": "USD", "dashboard_page": "Advanced Valuation and Downside Risk"},
            {"metric": "scenario_irr", "display_name": "Scenario IRR", "unit": "decimal", "dashboard_page": "Advanced Valuation and Downside Risk"},
            {"metric": "peak_revenue_year", "display_name": "Peak Revenue Year", "unit": "year", "dashboard_page": "Executive Planning Overview"},
            {"metric": "peak_fcf_year", "display_name": "Peak FCF Year", "unit": "year", "dashboard_page": "Executive Planning Overview"},
            {"metric": "payback_year", "display_name": "Payback Year", "unit": "year", "dashboard_page": "Advanced Valuation and Downside Risk"},
        ]
    )


def build_dashboard_pages() -> pd.DataFrame:
    return pd.DataFrame(
        [
            {"page_name": "Executive Planning Overview", "goal": "Summarize throughput, price exposure, cost pressure, cash generation, and the selected scenario view.", "primary_dataset": "fact_scenario_kpis.csv"},
            {"page_name": "Throughput and Production", "goal": "Track processed tonnes and copper production across the project profile.", "primary_dataset": "fact_annual_metrics.csv"},
            {"page_name": "Grade and Recovery", "goal": "Monitor ore quality and metallurgical performance trends.", "primary_dataset": "fact_annual_metrics.csv"},
            {"page_name": "Cost, Revenue and Cash Generation", "goal": "Track revenue, unit cost, EBITDA, operating cash flow, capex, and free cash flow.", "primary_dataset": "fact_annual_metrics.csv"},
            {"page_name": "Scenario Planning and Price Exposure", "goal": "Compare market and operating cases with explicit commodity price exposure.", "primary_dataset": "fact_scenario_kpis.csv"},
            {"page_name": "Advanced Valuation and Downside Risk", "goal": "Use NPV, IRR, Monte Carlo, and sensitivity as an advanced decision-support layer.", "primary_dataset": "fact_simulation_distribution.csv"},
            {"page_name": "Benchmark and Method Transparency", "goal": "Document comparability limits versus the workbook benchmark.", "primary_dataset": "benchmark_comparison.csv"},
        ]
    )


def build_powerbi_measure_catalog() -> pd.DataFrame:
    return pd.DataFrame(
        [
            {
                "measure_name": "Selected Scenario NPV",
                "table_name": "fact_scenario_kpis",
                "dax_template": 'Selected Scenario NPV = CALCULATE(MAX(fact_scenario_kpis[value]), fact_scenario_kpis[metric] = "scenario_npv_usd")',
                "format_hint": "Currency",
                "dashboard_page": "Advanced Valuation and Downside Risk",
                "description": "Advanced valuation output for the selected deterministic scenario.",
            },
            {
                "measure_name": "Base Case NPV",
                "table_name": "fact_scenario_kpis",
                "dax_template": 'Base Case NPV = CALCULATE(MAX(fact_scenario_kpis[value]), fact_scenario_kpis[metric] = "scenario_npv_usd", dim_scenario[scenario_id] = "base")',
                "format_hint": "Currency",
                "dashboard_page": "Advanced Valuation and Downside Risk",
                "description": "Reference NPV used when the dashboard needs a valuation anchor.",
            },
            {
                "measure_name": "Committee Downside NPV",
                "table_name": "fact_scenario_kpis",
                "dax_template": 'Committee Downside NPV = CALCULATE(MAX(fact_scenario_kpis[value]), fact_scenario_kpis[metric] = "scenario_npv_usd", dim_scenario[scenario_id] = "committee_downside")',
                "format_hint": "Currency",
                "dashboard_page": "Advanced Valuation and Downside Risk",
                "description": "Hard downside deterministic case for management and investment review.",
            },
            {
                "measure_name": "NPV Delta vs Base",
                "table_name": "fact_scenario_kpis",
                "dax_template": "NPV Delta vs Base = [Selected Scenario NPV] - [Base Case NPV]",
                "format_hint": "Currency",
                "dashboard_page": "Scenario Planning and Price Exposure",
                "description": "Change in scenario NPV relative to the reference planning case.",
            },
            {
                "measure_name": "Selected Scenario IRR",
                "table_name": "fact_scenario_kpis",
                "dax_template": 'Selected Scenario IRR = CALCULATE(MAX(fact_scenario_kpis[value]), fact_scenario_kpis[metric] = "scenario_irr")',
                "format_hint": "Percentage",
                "dashboard_page": "Advanced Valuation and Downside Risk",
                "description": "IRR for the selected deterministic scenario using explicit year-0 cash flows.",
            },
            {
                "measure_name": "Scenario Revenue",
                "table_name": "fact_scenario_kpis",
                "dax_template": 'Scenario Revenue = CALCULATE(MAX(fact_scenario_kpis[value]), fact_scenario_kpis[metric] = "total_revenue_usd")',
                "format_hint": "Currency",
                "dashboard_page": "Executive Planning Overview",
                "description": "Total revenue exposure over the project horizon for the selected scenario.",
            },
            {
                "measure_name": "Scenario EBITDA",
                "table_name": "fact_scenario_kpis",
                "dax_template": 'Scenario EBITDA = CALCULATE(MAX(fact_scenario_kpis[value]), fact_scenario_kpis[metric] = "total_ebitda_usd")',
                "format_hint": "Currency",
                "dashboard_page": "Executive Planning Overview",
                "description": "Total EBITDA over the project horizon for the selected scenario.",
            },
            {
                "measure_name": "Scenario Operating Cash Flow",
                "table_name": "fact_scenario_kpis",
                "dax_template": 'Scenario Operating Cash Flow = CALCULATE(MAX(fact_scenario_kpis[value]), fact_scenario_kpis[metric] = "total_operating_cash_flow_usd")',
                "format_hint": "Currency",
                "dashboard_page": "Executive Planning Overview",
                "description": "Total operating cash flow over the project horizon for the selected scenario.",
            },
            {
                "measure_name": "Scenario Free Cash Flow",
                "table_name": "fact_scenario_kpis",
                "dax_template": 'Scenario Free Cash Flow = CALCULATE(MAX(fact_scenario_kpis[value]), fact_scenario_kpis[metric] = "total_free_cash_flow_usd")',
                "format_hint": "Currency",
                "dashboard_page": "Executive Planning Overview",
                "description": "Total free cash flow over the project horizon for the selected scenario.",
            },
            {
                "measure_name": "Scenario Capex",
                "table_name": "fact_scenario_kpis",
                "dax_template": 'Scenario Capex = CALCULATE(MAX(fact_scenario_kpis[value]), fact_scenario_kpis[metric] = "total_capex_usd")',
                "format_hint": "Currency",
                "dashboard_page": "Executive Planning Overview",
                "description": "Total capex burden for the selected scenario.",
            },
            {
                "measure_name": "Scenario Payback Year",
                "table_name": "fact_scenario_kpis",
                "dax_template": 'Scenario Payback Year = CALCULATE(MAX(fact_scenario_kpis[value]), fact_scenario_kpis[metric] = "payback_year")',
                "format_hint": "Whole Number",
                "dashboard_page": "Advanced Valuation and Downside Risk",
                "description": "Payback timing for the selected scenario, when available.",
            },
            {
                "measure_name": "Scenario Avg Throughput",
                "table_name": "fact_scenario_kpis",
                "dax_template": 'Scenario Avg Throughput = CALCULATE(MAX(fact_scenario_kpis[value]), fact_scenario_kpis[metric] = "average_processed_tonnes")',
                "format_hint": "Whole Number",
                "dashboard_page": "Executive Planning Overview",
                "description": "Average processed tonnes in the selected scenario.",
            },
            {
                "measure_name": "Scenario Avg Copper Production",
                "table_name": "fact_scenario_kpis",
                "dax_template": 'Scenario Avg Copper Production = CALCULATE(MAX(fact_scenario_kpis[value]), fact_scenario_kpis[metric] = "average_copper_fine_lb")',
                "format_hint": "Whole Number",
                "dashboard_page": "Executive Planning Overview",
                "description": "Average annual copper production in pounds for the selected scenario.",
            },
            {
                "measure_name": "Scenario Avg Unit Opex",
                "table_name": "fact_scenario_kpis",
                "dax_template": 'Scenario Avg Unit Opex = CALCULATE(MAX(fact_scenario_kpis[value]), fact_scenario_kpis[metric] = "average_unit_opex_usd_per_tonne")',
                "format_hint": "Decimal Number",
                "dashboard_page": "Executive Planning Overview",
                "description": "Average unit operating cost for the selected scenario.",
            },
            {
                "measure_name": "Scenario EBITDA Margin Proxy",
                "table_name": "fact_scenario_kpis",
                "dax_template": 'Scenario EBITDA Margin Proxy = CALCULATE(MAX(fact_scenario_kpis[value]), fact_scenario_kpis[metric] = "ebitda_margin_proxy")',
                "format_hint": "Percentage",
                "dashboard_page": "Executive Planning Overview",
                "description": "EBITDA-to-revenue proxy used as a margin-style planning KPI.",
            },
            {
                "measure_name": "Annual Revenue",
                "table_name": "fact_annual_metrics",
                "dax_template": 'Annual Revenue = CALCULATE(SUM(fact_annual_metrics[value]), fact_annual_metrics[metric] = "revenue_usd")',
                "format_hint": "Currency",
                "dashboard_page": "Cost, Revenue and Cash Generation",
                "description": "Yearly revenue profile.",
            },
            {
                "measure_name": "Annual EBITDA",
                "table_name": "fact_annual_metrics",
                "dax_template": 'Annual EBITDA = CALCULATE(SUM(fact_annual_metrics[value]), fact_annual_metrics[metric] = "ebitda_usd")',
                "format_hint": "Currency",
                "dashboard_page": "Cost, Revenue and Cash Generation",
                "description": "Yearly EBITDA profile.",
            },
            {
                "measure_name": "Annual Operating Cash Flow",
                "table_name": "fact_annual_metrics",
                "dax_template": 'Annual Operating Cash Flow = CALCULATE(SUM(fact_annual_metrics[value]), fact_annual_metrics[metric] = "operating_cash_flow_usd")',
                "format_hint": "Currency",
                "dashboard_page": "Cost, Revenue and Cash Generation",
                "description": "Yearly operating cash flow profile.",
            },
            {
                "measure_name": "Annual Free Cash Flow",
                "table_name": "fact_annual_metrics",
                "dax_template": 'Annual Free Cash Flow = CALCULATE(SUM(fact_annual_metrics[value]), fact_annual_metrics[metric] = "free_cash_flow_usd")',
                "format_hint": "Currency",
                "dashboard_page": "Cost, Revenue and Cash Generation",
                "description": "Yearly free cash flow profile.",
            },
            {
                "measure_name": "Annual Capex",
                "table_name": "fact_annual_metrics",
                "dax_template": 'Annual Capex = CALCULATE(SUM(fact_annual_metrics[value]), fact_annual_metrics[metric] = "capex_usd")',
                "format_hint": "Currency",
                "dashboard_page": "Cost, Revenue and Cash Generation",
                "description": "Yearly capex profile.",
            },
            {
                "measure_name": "Annual Processed Tonnes",
                "table_name": "fact_annual_metrics",
                "dax_template": 'Annual Processed Tonnes = CALCULATE(SUM(fact_annual_metrics[value]), fact_annual_metrics[metric] = "expanded_tonnes")',
                "format_hint": "Whole Number",
                "dashboard_page": "Throughput and Production",
                "description": "Expanded throughput by project year.",
            },
            {
                "measure_name": "Annual Copper Fine Production",
                "table_name": "fact_annual_metrics",
                "dax_template": 'Annual Copper Fine Production = CALCULATE(SUM(fact_annual_metrics[value]), fact_annual_metrics[metric] = "copper_fine_lb")',
                "format_hint": "Whole Number",
                "dashboard_page": "Throughput and Production",
                "description": "Annual copper production in pounds.",
            },
            {
                "measure_name": "Annual Unit Opex",
                "table_name": "fact_annual_metrics",
                "dax_template": 'Annual Unit Opex = CALCULATE(AVERAGE(fact_annual_metrics[value]), fact_annual_metrics[metric] = "unit_opex_usd_per_tonne")',
                "format_hint": "Decimal Number",
                "dashboard_page": "Cost, Revenue and Cash Generation",
                "description": "Average unit operating cost by year.",
            },
            {
                "measure_name": "Annual Net Price",
                "table_name": "fact_annual_metrics",
                "dax_template": 'Annual Net Price = CALCULATE(AVERAGE(fact_annual_metrics[value]), fact_annual_metrics[metric] = "scenario_net_price_usd_per_lb")',
                "format_hint": "Decimal Number",
                "dashboard_page": "Scenario Planning and Price Exposure",
                "description": "Net realized copper price per pound by year.",
            },
            {
                "measure_name": "Annual Head Grade %",
                "table_name": "fact_annual_metrics",
                "dax_template": 'Annual Head Grade % = CALCULATE(AVERAGE(fact_annual_metrics[value]), fact_annual_metrics[metric] = "scenario_grade") * 100',
                "format_hint": "Percentage",
                "dashboard_page": "Grade and Recovery",
                "description": "Head grade expressed as a percentage for charting.",
            },
            {
                "measure_name": "Annual Recovery %",
                "table_name": "fact_annual_metrics",
                "dax_template": 'Annual Recovery % = CALCULATE(AVERAGE(fact_annual_metrics[value]), fact_annual_metrics[metric] = "scenario_recovery") * 100',
                "format_hint": "Percentage",
                "dashboard_page": "Grade and Recovery",
                "description": "Metallurgical recovery expressed as a percentage for charting.",
            },
            {
                "measure_name": "Expected NPV",
                "table_name": "simulation_summary",
                "dax_template": 'Expected NPV = CALCULATE(MAX(simulation_summary[value]), simulation_summary[metric] = "expected_npv_usd")',
                "format_hint": "Currency",
                "dashboard_page": "Advanced Valuation and Downside Risk",
                "description": "Expected NPV from the Monte Carlo simulation.",
            },
            {
                "measure_name": "Median NPV",
                "table_name": "simulation_summary",
                "dax_template": 'Median NPV = CALCULATE(MAX(simulation_summary[value]), simulation_summary[metric] = "median_npv_usd")',
                "format_hint": "Currency",
                "dashboard_page": "Advanced Valuation and Downside Risk",
                "description": "Median NPV from the Monte Carlo simulation.",
            },
            {
                "measure_name": "Probability of Loss",
                "table_name": "simulation_summary",
                "dax_template": 'Probability of Loss = CALCULATE(MAX(simulation_summary[value]), simulation_summary[metric] = "probability_of_loss")',
                "format_hint": "Percentage",
                "dashboard_page": "Advanced Valuation and Downside Risk",
                "description": "Probability that simulated NPV is below zero.",
            },
            {
                "measure_name": "VaR 5%",
                "table_name": "simulation_summary",
                "dax_template": 'VaR 5% = CALCULATE(MAX(simulation_summary[value]), simulation_summary[metric] = "var_usd")',
                "format_hint": "Currency",
                "dashboard_page": "Advanced Valuation and Downside Risk",
                "description": "5th percentile Value at Risk from the simulation.",
            },
            {
                "measure_name": "CVaR 5%",
                "table_name": "simulation_summary",
                "dax_template": 'CVaR 5% = CALCULATE(MAX(simulation_summary[value]), simulation_summary[metric] = "cvar_usd")',
                "format_hint": "Currency",
                "dashboard_page": "Advanced Valuation and Downside Risk",
                "description": "Average outcome beyond the 5th percentile threshold.",
            },
            {
                "measure_name": "Tornado Impact",
                "table_name": "fact_tornado_sensitivity",
                "dax_template": "Tornado Impact = MAX(fact_tornado_sensitivity[impact_vs_base_usd])",
                "format_hint": "Currency",
                "dashboard_page": "Advanced Valuation and Downside Risk",
                "description": "Directional impact versus the base case for a selected tornado bar.",
            },
        ]
    )
