-- Advanced Scenario / Risk Appendix Measures

-- Table: fact_annual_metrics
Annual Capex = CALCULATE(SUM(fact_annual_metrics[value]), fact_annual_metrics[metric] = "capex_usd")

Annual Copper Fine Production = CALCULATE(SUM(fact_annual_metrics[value]), fact_annual_metrics[metric] = "copper_fine_lb")

Annual EBITDA = CALCULATE(SUM(fact_annual_metrics[value]), fact_annual_metrics[metric] = "ebitda_usd")

Annual Free Cash Flow = CALCULATE(SUM(fact_annual_metrics[value]), fact_annual_metrics[metric] = "free_cash_flow_usd")

Annual Head Grade % = CALCULATE(AVERAGE(fact_annual_metrics[value]), fact_annual_metrics[metric] = "scenario_grade") * 100

Annual Net Price = CALCULATE(AVERAGE(fact_annual_metrics[value]), fact_annual_metrics[metric] = "scenario_net_price_usd_per_lb")

Annual Operating Cash Flow = CALCULATE(SUM(fact_annual_metrics[value]), fact_annual_metrics[metric] = "operating_cash_flow_usd")

Annual Processed Tonnes = CALCULATE(SUM(fact_annual_metrics[value]), fact_annual_metrics[metric] = "expanded_tonnes")

Annual Recovery % = CALCULATE(AVERAGE(fact_annual_metrics[value]), fact_annual_metrics[metric] = "scenario_recovery") * 100

Annual Revenue = CALCULATE(SUM(fact_annual_metrics[value]), fact_annual_metrics[metric] = "revenue_usd")

Annual Unit Opex = CALCULATE(AVERAGE(fact_annual_metrics[value]), fact_annual_metrics[metric] = "unit_opex_usd_per_tonne")


-- Table: fact_scenario_kpis
Base Case NPV = CALCULATE(MAX(fact_scenario_kpis[value]), fact_scenario_kpis[metric] = "scenario_npv_usd", dim_scenario[scenario_id] = "base")

Committee Downside NPV = CALCULATE(MAX(fact_scenario_kpis[value]), fact_scenario_kpis[metric] = "scenario_npv_usd", dim_scenario[scenario_id] = "committee_downside")

NPV Delta vs Base = [Selected Scenario NPV] - [Base Case NPV]

Scenario Avg Copper Production = CALCULATE(MAX(fact_scenario_kpis[value]), fact_scenario_kpis[metric] = "average_copper_fine_lb")

Scenario Avg Throughput = CALCULATE(MAX(fact_scenario_kpis[value]), fact_scenario_kpis[metric] = "average_processed_tonnes")

Scenario Avg Unit Opex = CALCULATE(MAX(fact_scenario_kpis[value]), fact_scenario_kpis[metric] = "average_unit_opex_usd_per_tonne")

Scenario Capex = CALCULATE(MAX(fact_scenario_kpis[value]), fact_scenario_kpis[metric] = "total_capex_usd")

Scenario EBITDA = CALCULATE(MAX(fact_scenario_kpis[value]), fact_scenario_kpis[metric] = "total_ebitda_usd")

Scenario EBITDA Margin Proxy = CALCULATE(MAX(fact_scenario_kpis[value]), fact_scenario_kpis[metric] = "ebitda_margin_proxy")

Scenario Free Cash Flow = CALCULATE(MAX(fact_scenario_kpis[value]), fact_scenario_kpis[metric] = "total_free_cash_flow_usd")

Scenario Operating Cash Flow = CALCULATE(MAX(fact_scenario_kpis[value]), fact_scenario_kpis[metric] = "total_operating_cash_flow_usd")

Scenario Payback Year = CALCULATE(MAX(fact_scenario_kpis[value]), fact_scenario_kpis[metric] = "payback_year")

Scenario Revenue = CALCULATE(MAX(fact_scenario_kpis[value]), fact_scenario_kpis[metric] = "total_revenue_usd")

Selected Scenario IRR = CALCULATE(MAX(fact_scenario_kpis[value]), fact_scenario_kpis[metric] = "scenario_irr")

Selected Scenario NPV = CALCULATE(MAX(fact_scenario_kpis[value]), fact_scenario_kpis[metric] = "scenario_npv_usd")


-- Table: fact_tornado_sensitivity
Tornado Impact = MAX(fact_tornado_sensitivity[impact_vs_base_usd])


-- Table: simulation_summary
CVaR 5% = CALCULATE(MAX(simulation_summary[value]), simulation_summary[metric] = "cvar_usd")

Expected NPV = CALCULATE(MAX(simulation_summary[value]), simulation_summary[metric] = "expected_npv_usd")

Median NPV = CALCULATE(MAX(simulation_summary[value]), simulation_summary[metric] = "median_npv_usd")

Probability of Loss = CALCULATE(MAX(simulation_summary[value]), simulation_summary[metric] = "probability_of_loss")

VaR 5% = CALCULATE(MAX(simulation_summary[value]), simulation_summary[metric] = "var_usd")
