let
    SourcePath = MonthlyOutputRoot & "\\mart_monthly_cost_margin.csv",
    Source = Csv.Document(
        File.Contents(SourcePath),
        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
    ),
    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    TypedColumns = Table.TransformColumnTypes(
        PromotedHeaders,
        {
            {"site_id", type text},
            {"site_name", type text},
            {"period", type text},
            {"month_start_date", type text},
            {"calendar_year", Int64.Type},
            {"calendar_month", Int64.Type},
            {"calendar_quarter", Int64.Type},
            {"month_label", type text},
            {"copper_price_usd_per_lb_plan", type number},
            {"copper_price_usd_per_lb_actual", type number},
            {"copper_price_usd_per_lb_variance", type number},
            {"copper_price_usd_per_lb_variance_pct", type number},
            {"net_realized_price_usd_per_lb_plan", type number},
            {"net_realized_price_usd_per_lb_actual", type number},
            {"net_realized_price_usd_per_lb_variance", type number},
            {"net_realized_price_usd_per_lb_variance_pct", type number},
            {"unit_cost_usd_per_tonne_plan", type number},
            {"unit_cost_usd_per_tonne_actual", type number},
            {"unit_cost_usd_per_tonne_variance", type number},
            {"unit_cost_usd_per_tonne_variance_pct", type number},
            {"operating_cost_usd_plan", type number},
            {"operating_cost_usd_actual", Int64.Type},
            {"operating_cost_usd_variance", type number},
            {"operating_cost_usd_variance_pct", type number},
            {"revenue_proxy_usd_plan", type number},
            {"revenue_proxy_usd_actual", type number},
            {"revenue_proxy_usd_variance", type number},
            {"revenue_proxy_usd_variance_pct", type number},
            {"ebitda_proxy_usd_plan", type number},
            {"ebitda_proxy_usd_actual", type number},
            {"ebitda_proxy_usd_variance", type number},
            {"ebitda_proxy_usd_variance_pct", type number},
            {"operating_cash_flow_proxy_usd_plan", type number},
            {"operating_cash_flow_proxy_usd_actual", type number},
            {"operating_cash_flow_proxy_usd_variance", type number},
            {"operating_cash_flow_proxy_usd_variance_pct", type number},
            {"free_cash_flow_proxy_usd_plan", type number},
            {"free_cash_flow_proxy_usd_actual", type number},
            {"free_cash_flow_proxy_usd_variance", type number},
            {"free_cash_flow_proxy_usd_variance_pct", type number},
            {"sustaining_capex_usd_plan", Int64.Type},
            {"sustaining_capex_usd_actual", Int64.Type},
            {"sustaining_capex_usd_variance", Int64.Type},
            {"sustaining_capex_usd_variance_pct", type number},
            {"working_capital_change_usd_plan", Int64.Type},
            {"working_capital_change_usd_actual", Int64.Type},
            {"working_capital_change_usd_variance", Int64.Type},
            {"working_capital_change_usd_variance_pct", type number},
            {"mining_cost_usd_actual", Int64.Type},
            {"processing_cost_usd_actual", Int64.Type},
            {"ga_cost_usd_actual", Int64.Type},
            {"site_positive_cost_variance_usd", Int64.Type},
            {"site_cost_pressure_share_pct", type number},
            {"top_cost_center", type text},
            {"top_cost_center_variance_usd", Int64.Type},
            {"top_cost_center_margin_pressure_share_pct", type number},
            {"overall_alert_level", type text},
            {"primary_alert_metric", type text},
            {"primary_alert_message", type text},
            {"data_classification", type text},
            {"sample_data_flag", type logical}
        }
    )
in
    TypedColumns
